### ISSUE TITLE
Encounter errors when attempting to run the java example (TimeAndSales) and the bridge test

### ISSUE THREAD

**Issue by zundra** [jeog/TOSDataBridge#11]
I've also run through the troubleshooting tips to ensure everything was configured properly:

io.github.jeog.tosdatabridge.TOSDataBridge$CLibException: CLib call [TOSDB_AddTopic] failed; ERROR_DECREMENT_BASE(-2)
	at io.github.jeog.tosdatabridge.DataBlock.addTopic(DataBlock.java:329)
	at Test.testBlock1(Test.java:175)
	at Test.main(Test.java:72)
*** DONE (FAILURE) ***

**Comment by jeog** [comment]
First,  double check your JRE build matches the dll and the engine. Most errors like this tend to be an incompatibility between the JRE, lib, and/or engine.
```
C:\> java -version
```
if 64-bit VM you should be using the x64 version of the dll and engine.

Did you compile/run TOSDataBridgeTest.java yourself or did you run CompileAndRun.bat ? The latter assumes a 64bit VM.
