### ISSUE TITLE
Cannot get CUSTOM data 

### ISSUE THREAD

**Issue by xxwikkixx** [jeog/TOSDataBridge#20]
Hey,

I am trying to get my CUSTOM study data returned but it kept failing so I setup another CUSTOM field according to your tutorial just to test and make sure I wasnt doing anything wrong but still I dont get anything returned. [https://github.com/jeog/TOSDataBridge/blob/master/README_DETAILS.md#custom-topics](url)

I keep getting this error.  

`+ Using Module(s)  C:\TOSDataBridge\bin\Release\x64\tos-databridge-0.9-x64.dll
                   C:\TOSDataBridge\bin\Release\x64/_tos-databridge-x64.dll
+ Last Update: Thu Sep 26 19:21:45 2019
+ Process ID: 19376
+ Succesfully Connected to Service\Engine
+ Succesfully Connected to TOS
Sleeping for 10 second
Traceback (most recent call last):
  File "a:/git/Harmonic Patterns/TOSTest.py", line 89, in <module>
    tosStudyData()
  File "a:/git/Harmonic Patterns/TOSTest.py", line 78, in tosStudyData
    val = block.get("SPY", "CUSTOM9", date_time=False)
  File "C:\python37\lib\site-packages\tosdb\_win.py", line 636, in get
    raise TOSDB_DataError("data not available at this index yet " +
tosdb._common.TOSDB_DataError: data not available at this index yet (disable check_indx to avoid this error)
+ Closing Blocks
+ Disconnecting From Service \ Engine
+ Closing Module(s)  C:\TOSDataBridge\bin\Release\x64\tos-databridge-0.9-x64.dll
                     C:\TOSDataBridge\bin\Release\x64/_tos-databridge-x64.dll`

I put the check_index flag as False just to test it out and I dont get any data in there but an empty list.

**Comment by xxwikkixx** [comment]
Alright I made some progress and now I have reached the stage where I am getting the "loading" problem. 
Could you please clear up this part of the steps for me. I am not sure what I need to do in TOS.

> To export this CUSTOM quote via TOSDataBridge:
>Add this custom quote to at least one widget/window in TOS.
>Add the symbols you want to export to THAT widget/window.
>Add the appropriate topic to your block, i.e topic 'CUSTOM1' for 'CUSTOM 1'.
>Add the symbols/items you added in #2 to your block. (Symbols added to the block but not to TOS, will only return 'loading'.)

**Comment by xxwikkixx** [comment]
Never mind lol, I fixed everything.
